name: Build and Deploy hero-app project
on:
  push:	
    branches:	
      - master

jobs:
  hero-app-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: cd yarn install, build
        run: |
          cd hero-app  # 进入项目目录
          yarn         # 安装依赖
          yarn build --prod --base-href /ng-apps/hero-app/ # 构建项目

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.personal_token }}
        publish_dir: ./hero-app/dist # 发布目录
        publish_branch: gh-pages # 发布分支